# Generated by Django 2.2.2 on 2019-06-19 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0005_auto_20190619_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='dislike_users',
            field=models.ManyToManyField(blank=True, related_name='dislike_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
